inputs:
   - name : ${HOME}/data/eviz/merra2/MERRA2_400.inst6_3d_ana_Np.20211123.nc4
     description: MERRA2 inst6_3d_ana_Np
     to_plot:
         H: yz

outputs:
    output_dir: ${HOME}/scratch/eviz/output/gridded_yz
    print_to_file: yes
    visualization:
        style: publication # Options: default, transparent, darkmode


