inputs:
   - name : ${HOME}/data/eviz/merra2/MERRA2_400.inst6_3d_ana_Np.20211123.nc4
     to_plot:
         SLP: xy

outputs:
    output_dir: ${HOME}/scratch/eviz/output/gridded_xy
    print_to_file: yes
    visualization:
        style: publication # Options: default, transparent, darkmode


