inputs:
   - name     : ${HOME}/data/eviz/airnow/HourlyAQObs*
     description: 25 μm particulate matter
     reader   : csv
     to_plot  :
        PM25: sc

#for_inputs:
#    plot_backend: hvplot

outputs:
    output_dir: ${HOME}/scratch/eviz/output/obs
    print_to_file: yes
    filename: airnow_stations_map
 
