inputs:
- name: /Users/ccruz/data/eviz/gridded/MERRA2_T.20250601.nc4
  to_plot:
    T: xy
outputs:
  output_dir: /Users/ccruz/scratch/eviz/output/gridded_xy
  print_to_file: true
  filename: xy_plot_conus_lambert_projection
